In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../day-03/data/sales_data.csv")

In [3]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

## Aggregations

In [4]:
df['Sales_Amount'].sum()

np.float64(5019265.2299999995)

In [5]:
df['Sales_Amount'].mean()

np.float64(5019.265229999999)

In [6]:
df['Sales_Amount'].min()

100.12

In [7]:
df['Sales_Amount'].max()

9989.04

In [8]:
df['Sales_Amount'].count()

np.int64(1000)

## groupby()

In [9]:
# Total_sales by Categoeries 

df.groupby('Product_Category')['Sales_Amount'].sum()

Product_Category
Clothing       1313474.36
Electronics    1243499.64
Food           1201773.54
Furniture      1260517.69
Name: Sales_Amount, dtype: float64

In [12]:
# Multiple statistics:

df.groupby('Product_Category')['Sales_Amount'].agg(['sum','mean','count','min','max'])

                         sum         mean  count     min      max
Product_Category
Clothing          1313474.36  4901.023731    268  100.12  9972.66
Electronics       1243499.64  5054.876585    246  189.48  9914.15
Food              1201773.54  5317.582035    226  114.59  9989.04
Furniture         1260517.69  4848.144962    260  113.40  9976.52

In [14]:
# Multiple grouping columns:

df.groupby(['Region','Product_Category'])['Sales_Amount'].sum()

Region  Product_Category
East    Clothing            356670.40
        Electronics         303101.42
        Food                325864.87
        Furniture           274156.24
North   Clothing            372977.22
        Electronics         342666.29
        Food                258985.65
        Furniture           394983.35
South   Clothing            269517.74
        Electronics         293663.96
        Food                301187.51
        Furniture           289881.65
West    Clothing            314309.00
        Electronics         304067.97
        Food                315735.51
        Furniture           301496.45
Name: Sales_Amount, dtype: float64